# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactions', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('sts_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=20, null=True)),
                ('mname', models.CharField(blank=True, max_length=20, null=True)),
                ('lname', models.CharField(blank=True, max_length=20, null=True)),
                ('student_id', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('maritalstatus', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('user_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(blank=True, max_length=20, null=True)),
                ('cluster_code', models.CharField(blank=True, max_length=20, null=True)),
                ('prof_id', models.CharField(blank=True, max_length=20, null=True)),
                ('schedule_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.Student'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.Subjects'),
        ),
        migrations.AddField(
            model_name='account',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.SchoolInfo'),
        ),
    ]
